variables:
  - name: serviceConnectionName
    value: 'devopspro-demo-sc'

  - name: azureDevopsEnvironment
    value: 'demo-env'

  - name: agentPoolName
    value: 'Ubuntu-22.04'

  - name: keyVaultName
    value: 'jcassanji-demo-kv'

  - name: tfBackendConfigPath
    value: '$(Agent.BuildDirectory)/src/iac/config/backend/${{ parameters.environment }}/demo.backend.conf'

  - name: tfVariablesFilePath
    value: '$(Agent.BuildDirectory)/src/iac/config/variables/${{ parameters.environment }}/variables.tfvars'

  - name: tfProjectPath
    value: '$(Agent.BuildDirectory)/src/iac'