variables:
  - name: serviceConnectionName
    value: 'devopspro-demo-sc'

  - name: agentPoolName
    value: 'Ubuntu-22.04'

  - name: tfBackendConfigPath
    value: './config/backend/dev/demo.backend.conf'

  - name: tfBackendConfigPath
    value: './config/variables/dev/variables.tfvars'

  - name: tfProjectPath
    value: './iac'