variables:
  - name: serviceConnectionName
    value: 'devopspro-demo-sc'

  - name: agentPoolName
    value: 'Ubuntu-22.04'

  - name: tfBackendConfigPath
    value: '$(System.DefaultWorkingDirectory)/iac/config/backend/dev/demo.backend.conf'

  - name: tfVariablesFilePath
    value: '$(System.DefaultWorkingDirectory)/iac/config/variables/dev/variables.tfvars'

  - name: tfProjectPath
    value: '$(System.DefaultWorkingDirectory)/iac'