trigger:
  batch: true
  branches:
    include:
      - main

variables:
  - template: ./templates/variables/settings.yml

stages:
  - stage: IAC_CI
    pool:
      vmImage: $(agentPoolName)
    displayName: IAC CI
    jobs:
      - job: validation
        displayName: Validation
        steps:
          - checkout: self
            path: src
          - template: ./templates/steps/load-credentials.yml
            parameters:
              serviceConnectionName: $(serviceConnectionName)
          - template: ./templates/steps/load-secrets.yml
            parameters:
              keyVaultName: $(keyVaultName)
              serviceConnectionName: $(serviceConnectionName)
          - template: ./templates/steps/terraform-init.yml
            parameters:
              tfBackendConfigPath: $(tfBackendConfigPath)
              tfProjectPath: $(tfProjectPath) 
          - template: ./templates/steps/terraform-validate.yml
            parameters:
              tfProjectPath: $(tfProjectPath)      
          - template: ./templates/steps/terraform-plan.yml
            parameters:
              tfProjectPath: $(tfProjectPath)
              tfVariablesFilePath: $(tfVariablesFilePath) 

  # - stage: IAC_CD
  #   displayName: IAC CD
  #   jobs:
  #     - job: deploy
  #       displayName: Deploy
  #       steps:
  #         - template: ./templates/steps/load-credentials.yml
  #           parameters:
  #             serviceConnectionName: 'ADD PARAMETER'
  #         - template: ./templates/steps/terraform-init.yml
  #           parameters:
  #             spnName: 'ADD PARAMETER' 
  #         - template: ./templates/steps/terraform-apply.yml
  #           parameters:
  #             spnName: 'ADD PARAMETER' 