trigger:
  batch: true
  branches:
    include:
      - main

resources:
  repositories:
  - repository: IAC
    type: git
    name: joaocassanji/devops4devs-terraform-demo.git
    ref: main
    trigger:
    - main

variables:
  - template: ./templates/variables/settings.yml

stages:
  - stage: IAC_CI
    pool:
      vmImage: $(agentPoolName)
    displayName: IAC CI
    jobs:
      - job: validation
        displayName: Validation
        steps:
          - checkout: git@github.com:joaocassanji/devops4devs-terraform-demo.git
          - template: ./templates/steps/load-credentials.yml
            parameters:
              serviceConnectionName: $(serviceConnectionName)
  #         - template: ./templates/steps/terraform-init.yml
  #           parameters:
  #             tfBackendConfigPath: 'ADD PARAMETER' 
  #             tfProjectPath: 'ADD PARAMETER' 
  #         - template: ./templates/steps/terraform-validate.yml
  #           parameters:
  #             tfBackendConfigPath: 'ADD PARAMETER'       
  #         - template: ./templates/steps/terraform-plan.yml
  #           parameters:
  #             spnName: 'ADD PARAMETER' 

  # - stage: IAC_CD
  #   displayName: IAC CD
  #   jobs:
  #     - job: deploy
  #       displayName: Deploy
  #       steps:
  #         - template: ./templates/steps/load-credentials.yml
  #           parameters:
  #             serviceConnectionName: 'ADD PARAMETER'
  #         - template: ./templates/steps/terraform-init.yml
  #           parameters:
  #             spnName: 'ADD PARAMETER' 
  #         - template: ./templates/steps/terraform-apply.yml
  #           parameters:
  #             spnName: 'ADD PARAMETER' 